version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  # Python Backend (Port 8001)
  backend:
    build: ./backend
    restart: always
    env_file: ./backend/.env
    ports:
      - "8001:8001"
    networks:
      - app-network

  # React/Web Frontend (Port 3000)
  frontend:
    build: ./frontend
    restart: always
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
    networks:
      - app-network

  # Laravel Admin Panel (Port 8000)
  admin:
    build: ./admin
    restart: always
    env_file: ./admin/.env
    ports:
      - "8000:8000"
    volumes:
      - ./admin:/var/www
    networks:
      - app-network
    depends_on:
      - backend
    # Laravel'in dahili sunucusunu başlatalım (En hızlı çözüm)
    command: php artisan serve --host=0.0.0.0 --port=8000